// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzutgsdrhsebhsuqyeqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6dXRnc2RyaHNlYmhzdXF5ZXFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMzQ3NTIsImV4cCI6MjA2MjYxMDc1Mn0.qhVCR_j2PRY-wQN-j_RljZ30OaQuGuy0WRBwuig2HKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);